name: flame_xml
description: xml parser using Flame game engine
version: 0.1.0
homepage: https://github.com/webcyou-org/flame_xml

environment:
  sdk: '>=2.19.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.6.0
  xml: ^6.2.2
  tiled: ^0.10.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/tiles/
